import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Space from './components/Space'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className={`text-[8px]  fixed z-50 items-center gap-[6px]  top-8  right-8  `}
        >
          <Space></Space>
        </div>
        {children}
      </body>
    </html>
  )
}
